/**
 *
 *  ProfessionalHistory.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace culture_hub
{

class ProfessionalHistory
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _project;
        static const std::string _node_id;
        static const std::string _sort;
        static const std::string _event_date;
        static const std::string _event_description;
        static const std::string _fee;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit ProfessionalHistory(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit ProfessionalHistory(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    ProfessionalHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    ProfessionalHistory() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column project  */
    ///Get the value of the column project, returns the default value if the column is null
    const std::string &getValueOfProject() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProject() const noexcept;
    ///Set the value of the column project
    void setProject(const std::string &pProject) noexcept;
    void setProject(std::string &&pProject) noexcept;

    /**  For column node_id  */
    ///Get the value of the column node_id, returns the default value if the column is null
    const int32_t &getValueOfNodeId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getNodeId() const noexcept;
    ///Set the value of the column node_id
    void setNodeId(const int32_t &pNodeId) noexcept;

    /**  For column sort  */
    ///Get the value of the column sort, returns the default value if the column is null
    const std::string &getValueOfSort() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSort() const noexcept;
    ///Set the value of the column sort
    void setSort(const std::string &pSort) noexcept;
    void setSort(std::string &&pSort) noexcept;

    /**  For column event_date  */
    ///Get the value of the column event_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfEventDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getEventDate() const noexcept;
    ///Set the value of the column event_date
    void setEventDate(const ::trantor::Date &pEventDate) noexcept;

    /**  For column event_description  */
    ///Get the value of the column event_description, returns the default value if the column is null
    const std::string &getValueOfEventDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEventDescription() const noexcept;
    ///Set the value of the column event_description
    void setEventDescription(const std::string &pEventDescription) noexcept;
    void setEventDescription(std::string &&pEventDescription) noexcept;
    void setEventDescriptionToNull() noexcept;

    /**  For column fee  */
    ///Get the value of the column fee, returns the default value if the column is null
    const std::string &getValueOfFee() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getFee() const noexcept;
    ///Set the value of the column fee
    void setFee(const std::string &pFee) noexcept;
    void setFee(std::string &&pFee) noexcept;
    void setFeeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<ProfessionalHistory>;
    friend drogon::orm::BaseBuilder<ProfessionalHistory, true, true>;
    friend drogon::orm::BaseBuilder<ProfessionalHistory, true, false>;
    friend drogon::orm::BaseBuilder<ProfessionalHistory, false, true>;
    friend drogon::orm::BaseBuilder<ProfessionalHistory, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<ProfessionalHistory>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> project_;
    std::shared_ptr<int32_t> nodeId_;
    std::shared_ptr<std::string> sort_;
    std::shared_ptr<::trantor::Date> eventDate_;
    std::shared_ptr<std::string> eventDescription_;
    std::shared_ptr<std::string> fee_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "project,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "node_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "sort,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "event_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "event_description,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "fee,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace culture_hub
} // namespace drogon_model
