/**
 *
 *  ProfessionalHistory.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ProfessionalHistory.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::culture_hub;

const std::string ProfessionalHistory::Cols::_id = "id";
const std::string ProfessionalHistory::Cols::_project = "project";
const std::string ProfessionalHistory::Cols::_node_id = "node_id";
const std::string ProfessionalHistory::Cols::_sort = "sort";
const std::string ProfessionalHistory::Cols::_event_date = "event_date";
const std::string ProfessionalHistory::Cols::_event_description = "event_description";
const std::string ProfessionalHistory::Cols::_fee = "fee";
const std::string ProfessionalHistory::primaryKeyName = "id";
const bool ProfessionalHistory::hasPrimaryKey = true;
const std::string ProfessionalHistory::tableName = "professional_history";

const std::vector<typename ProfessionalHistory::MetaData> ProfessionalHistory::metaData_={
{"id","int32_t","int",4,1,1,1},
{"project","std::string","varchar(50)",50,0,0,1},
{"node_id","int32_t","int",4,0,0,1},
{"sort","std::string","set('concert','workshop','conference','exhibitions','residence','other')",0,0,0,1},
{"event_date","::trantor::Date","date",0,0,0,1},
{"event_description","std::string","text",0,0,0,0},
{"fee","std::string","decimal(5,2)",0,0,0,0}
};
const std::string &ProfessionalHistory::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ProfessionalHistory::ProfessionalHistory(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["project"].isNull())
        {
            project_=std::make_shared<std::string>(r["project"].as<std::string>());
        }
        if(!r["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r["node_id"].as<int32_t>());
        }
        if(!r["sort"].isNull())
        {
            sort_=std::make_shared<std::string>(r["sort"].as<std::string>());
        }
        if(!r["event_date"].isNull())
        {
            auto daysStr = r["event_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["event_description"].isNull())
        {
            eventDescription_=std::make_shared<std::string>(r["event_description"].as<std::string>());
        }
        if(!r["fee"].isNull())
        {
            fee_=std::make_shared<std::string>(r["fee"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            project_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            nodeId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            sort_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            eventDescription_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            fee_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ProfessionalHistory::ProfessionalHistory(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            project_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sort_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eventDescription_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            fee_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

ProfessionalHistory::ProfessionalHistory(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("project"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["project"].isNull())
        {
            project_=std::make_shared<std::string>(pJson["project"].asString());
        }
    }
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("sort"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["sort"].isNull())
        {
            sort_=std::make_shared<std::string>(pJson["sort"].asString());
        }
    }
    if(pJson.isMember("event_date"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["event_date"].isNull())
        {
            auto daysStr = pJson["event_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("event_description"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["event_description"].isNull())
        {
            eventDescription_=std::make_shared<std::string>(pJson["event_description"].asString());
        }
    }
    if(pJson.isMember("fee"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["fee"].isNull())
        {
            fee_=std::make_shared<std::string>(pJson["fee"].asString());
        }
    }
}

void ProfessionalHistory::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            project_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            sort_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            eventDescription_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            fee_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
}

void ProfessionalHistory::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("project"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["project"].isNull())
        {
            project_=std::make_shared<std::string>(pJson["project"].asString());
        }
    }
    if(pJson.isMember("node_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["node_id"].isNull())
        {
            nodeId_=std::make_shared<int32_t>((int32_t)pJson["node_id"].asInt64());
        }
    }
    if(pJson.isMember("sort"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["sort"].isNull())
        {
            sort_=std::make_shared<std::string>(pJson["sort"].asString());
        }
    }
    if(pJson.isMember("event_date"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["event_date"].isNull())
        {
            auto daysStr = pJson["event_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            eventDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("event_description"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["event_description"].isNull())
        {
            eventDescription_=std::make_shared<std::string>(pJson["event_description"].asString());
        }
    }
    if(pJson.isMember("fee"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["fee"].isNull())
        {
            fee_=std::make_shared<std::string>(pJson["fee"].asString());
        }
    }
}

const int32_t &ProfessionalHistory::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProfessionalHistory::getId() const noexcept
{
    return id_;
}
void ProfessionalHistory::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename ProfessionalHistory::PrimaryKeyType & ProfessionalHistory::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ProfessionalHistory::getValueOfProject() const noexcept
{
    static const std::string defaultValue = std::string();
    if(project_)
        return *project_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProfessionalHistory::getProject() const noexcept
{
    return project_;
}
void ProfessionalHistory::setProject(const std::string &pProject) noexcept
{
    project_ = std::make_shared<std::string>(pProject);
    dirtyFlag_[1] = true;
}
void ProfessionalHistory::setProject(std::string &&pProject) noexcept
{
    project_ = std::make_shared<std::string>(std::move(pProject));
    dirtyFlag_[1] = true;
}

const int32_t &ProfessionalHistory::getValueOfNodeId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nodeId_)
        return *nodeId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &ProfessionalHistory::getNodeId() const noexcept
{
    return nodeId_;
}
void ProfessionalHistory::setNodeId(const int32_t &pNodeId) noexcept
{
    nodeId_ = std::make_shared<int32_t>(pNodeId);
    dirtyFlag_[2] = true;
}

const std::string &ProfessionalHistory::getValueOfSort() const noexcept
{
    static const std::string defaultValue = std::string();
    if(sort_)
        return *sort_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProfessionalHistory::getSort() const noexcept
{
    return sort_;
}
void ProfessionalHistory::setSort(const std::string &pSort) noexcept
{
    sort_ = std::make_shared<std::string>(pSort);
    dirtyFlag_[3] = true;
}
void ProfessionalHistory::setSort(std::string &&pSort) noexcept
{
    sort_ = std::make_shared<std::string>(std::move(pSort));
    dirtyFlag_[3] = true;
}

const ::trantor::Date &ProfessionalHistory::getValueOfEventDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(eventDate_)
        return *eventDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProfessionalHistory::getEventDate() const noexcept
{
    return eventDate_;
}
void ProfessionalHistory::setEventDate(const ::trantor::Date &pEventDate) noexcept
{
    eventDate_ = std::make_shared<::trantor::Date>(pEventDate.roundDay());
    dirtyFlag_[4] = true;
}

const std::string &ProfessionalHistory::getValueOfEventDescription() const noexcept
{
    static const std::string defaultValue = std::string();
    if(eventDescription_)
        return *eventDescription_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProfessionalHistory::getEventDescription() const noexcept
{
    return eventDescription_;
}
void ProfessionalHistory::setEventDescription(const std::string &pEventDescription) noexcept
{
    eventDescription_ = std::make_shared<std::string>(pEventDescription);
    dirtyFlag_[5] = true;
}
void ProfessionalHistory::setEventDescription(std::string &&pEventDescription) noexcept
{
    eventDescription_ = std::make_shared<std::string>(std::move(pEventDescription));
    dirtyFlag_[5] = true;
}
void ProfessionalHistory::setEventDescriptionToNull() noexcept
{
    eventDescription_.reset();
    dirtyFlag_[5] = true;
}

const std::string &ProfessionalHistory::getValueOfFee() const noexcept
{
    static const std::string defaultValue = std::string();
    if(fee_)
        return *fee_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProfessionalHistory::getFee() const noexcept
{
    return fee_;
}
void ProfessionalHistory::setFee(const std::string &pFee) noexcept
{
    fee_ = std::make_shared<std::string>(pFee);
    dirtyFlag_[6] = true;
}
void ProfessionalHistory::setFee(std::string &&pFee) noexcept
{
    fee_ = std::make_shared<std::string>(std::move(pFee));
    dirtyFlag_[6] = true;
}
void ProfessionalHistory::setFeeToNull() noexcept
{
    fee_.reset();
    dirtyFlag_[6] = true;
}

void ProfessionalHistory::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &ProfessionalHistory::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "project",
        "node_id",
        "sort",
        "event_date",
        "event_description",
        "fee"
    };
    return inCols;
}

void ProfessionalHistory::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProject())
        {
            binder << getValueOfProject();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNodeId())
        {
            binder << getValueOfNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSort())
        {
            binder << getValueOfSort();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEventDate())
        {
            binder << getValueOfEventDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEventDescription())
        {
            binder << getValueOfEventDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getFee())
        {
            binder << getValueOfFee();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ProfessionalHistory::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void ProfessionalHistory::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getProject())
        {
            binder << getValueOfProject();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNodeId())
        {
            binder << getValueOfNodeId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSort())
        {
            binder << getValueOfSort();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEventDate())
        {
            binder << getValueOfEventDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEventDescription())
        {
            binder << getValueOfEventDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getFee())
        {
            binder << getValueOfFee();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ProfessionalHistory::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProject())
    {
        ret["project"]=getValueOfProject();
    }
    else
    {
        ret["project"]=Json::Value();
    }
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getSort())
    {
        ret["sort"]=getValueOfSort();
    }
    else
    {
        ret["sort"]=Json::Value();
    }
    if(getEventDate())
    {
        ret["event_date"]=getEventDate()->toDbStringLocal();
    }
    else
    {
        ret["event_date"]=Json::Value();
    }
    if(getEventDescription())
    {
        ret["event_description"]=getValueOfEventDescription();
    }
    else
    {
        ret["event_description"]=Json::Value();
    }
    if(getFee())
    {
        ret["fee"]=getValueOfFee();
    }
    else
    {
        ret["fee"]=Json::Value();
    }
    return ret;
}

std::string ProfessionalHistory::toString() const
{
    return toJson().toStyledString();
}

Json::Value ProfessionalHistory::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProject())
            {
                ret[pMasqueradingVector[1]]=getValueOfProject();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNodeId())
            {
                ret[pMasqueradingVector[2]]=getValueOfNodeId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSort())
            {
                ret[pMasqueradingVector[3]]=getValueOfSort();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEventDate())
            {
                ret[pMasqueradingVector[4]]=getEventDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEventDescription())
            {
                ret[pMasqueradingVector[5]]=getValueOfEventDescription();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getFee())
            {
                ret[pMasqueradingVector[6]]=getValueOfFee();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProject())
    {
        ret["project"]=getValueOfProject();
    }
    else
    {
        ret["project"]=Json::Value();
    }
    if(getNodeId())
    {
        ret["node_id"]=getValueOfNodeId();
    }
    else
    {
        ret["node_id"]=Json::Value();
    }
    if(getSort())
    {
        ret["sort"]=getValueOfSort();
    }
    else
    {
        ret["sort"]=Json::Value();
    }
    if(getEventDate())
    {
        ret["event_date"]=getEventDate()->toDbStringLocal();
    }
    else
    {
        ret["event_date"]=Json::Value();
    }
    if(getEventDescription())
    {
        ret["event_description"]=getValueOfEventDescription();
    }
    else
    {
        ret["event_description"]=Json::Value();
    }
    if(getFee())
    {
        ret["fee"]=getValueOfFee();
    }
    else
    {
        ret["fee"]=Json::Value();
    }
    return ret;
}

bool ProfessionalHistory::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("project"))
    {
        if(!validJsonOfField(1, "project", pJson["project"], err, true))
            return false;
    }
    else
    {
        err="The project column cannot be null";
        return false;
    }
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(2, "node_id", pJson["node_id"], err, true))
            return false;
    }
    else
    {
        err="The node_id column cannot be null";
        return false;
    }
    if(pJson.isMember("sort"))
    {
        if(!validJsonOfField(3, "sort", pJson["sort"], err, true))
            return false;
    }
    else
    {
        err="The sort column cannot be null";
        return false;
    }
    if(pJson.isMember("event_date"))
    {
        if(!validJsonOfField(4, "event_date", pJson["event_date"], err, true))
            return false;
    }
    else
    {
        err="The event_date column cannot be null";
        return false;
    }
    if(pJson.isMember("event_description"))
    {
        if(!validJsonOfField(5, "event_description", pJson["event_description"], err, true))
            return false;
    }
    if(pJson.isMember("fee"))
    {
        if(!validJsonOfField(6, "fee", pJson["fee"], err, true))
            return false;
    }
    return true;
}
bool ProfessionalHistory::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProfessionalHistory::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("project"))
    {
        if(!validJsonOfField(1, "project", pJson["project"], err, false))
            return false;
    }
    if(pJson.isMember("node_id"))
    {
        if(!validJsonOfField(2, "node_id", pJson["node_id"], err, false))
            return false;
    }
    if(pJson.isMember("sort"))
    {
        if(!validJsonOfField(3, "sort", pJson["sort"], err, false))
            return false;
    }
    if(pJson.isMember("event_date"))
    {
        if(!validJsonOfField(4, "event_date", pJson["event_date"], err, false))
            return false;
    }
    if(pJson.isMember("event_description"))
    {
        if(!validJsonOfField(5, "event_description", pJson["event_description"], err, false))
            return false;
    }
    if(pJson.isMember("fee"))
    {
        if(!validJsonOfField(6, "fee", pJson["fee"], err, false))
            return false;
    }
    return true;
}
bool ProfessionalHistory::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProfessionalHistory::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && 
            std::string(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
